Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@lgouveia9 
rancher
/
pipeline-example-go
4
29245
Code
Issues
Pull requests
1
Actions
Projects
Wiki
Security
Insights
pipeline-example-go/deployment.yaml
@gitlawr
gitlawr use IMAGE variable
Latest commit 072af0a on 10 Sep 2018
 History
 1 contributor
36 lines (36 sloc)  651 Bytes
  
kind: Service
apiVersion: v1
metadata:
  name: helloserver-service
spec:
  selector:
    app: helloserver
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver
  labels:
    app: helloserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver
  template:
    metadata:
      labels:
        app: helloserver
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: helloserver
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
